name: "Setup incus-client"
author: shellhazard
description: Set up Incus on a Github Runner in Ubuntu.

inputs:
  remote_host:
    required: false

secrets:
  # Generate these locally and copy them from ~/.config/incus.
  # Delete and regenerate them afterwards; you should be using a separate set of certs in CI.
  incus_client_cert:
    required: true
  incus_client_key:
    required: true

runs:
  using: composite
  steps:
    - name: Check platform
      run: if [[ "${{ runner.os }}" != "Linux" ]]; then echo "::error::Unsupported platform - ${{ runner.os }}"; exit 1; fi
      shell: bash

    - name: Install incus-client
      shell: bash
      run: bash install.sh

    - name: Place certificates in expected location
      shell: bash
      run: |
        echo ${{ secrets.incus_client_cert }} | tee ~/.config/client.crt
        echo ${{ secrets.incus_client_key }} | tee ~/.config/client.key
    
    - name: Add user to incus-admin group
      shell: bash
      run: |
        sudo adduser $USER incus-admin
        newgrp incus-admin

    - name: Add remote if specified
      shell: bash
      run: |
        [[ "${{ inputs.remote_host }}" = true ]] && incus remote add ${{ inputs.remote_host }} --accept-certificate
